GET http://localhost:3000/usuarios
###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "usuario": "Juaum"
}
###

GET http://localhost:3000/usuarios/3
###

DELETE http://localhost:3000/usuarios/3
###

PUT http://localhost:3000/usuarios/3
Content-Type: application/json

{
    "usuario": "JuaumAtualizado"
}
###